export const nepalProvinceCities = {
  koshi: [
    "Bhojpur",
    "Shadananda",
    "Dhankuta",
    "Mahalaxmi",
    "Pakhribas",
    "Deumai",
    "Ilam",
    "Mai",
    "Suryodaya",
    "Arjundhara",
    "Bhadrapur",
    "Birtamod",
    "Damak",
    "Gauradaha",
    "Kankai",
    "Mechinagar",
    "Shivasatakshi",
    "Diktel Rupakot Majhuwagadhi",
    "Halesi Tuwachung",
    "Belbari",
    "Biratnagar",
    "Letang",
    "Pathari Shanishchare",
    "Rangeli",
    "Ratuwamai",
    "Sundar Haraincha",
    "Sunawarshi",
    "Urlabari",
    "Siddhicharan",
    "Phidim",
    "Chainpur",
    "Dharmadevi",
    "Khandbari",
    "Madi",
    "Panchkhapan",
    "Solududhkunda",
    "Barahachhetra",
    "Dharan",
    "Duhabi",
    "Inaruwa",
    "Itahari",
    "Ramdhuni",
    "Phungling",
    "Laligurans",
    "Myanglung",
    "Belaka",
    "Chaudandigadhi",
    "Katari",
    "Triyuga"
  ],

  madhesh: [
    "Jitpursimara",
    "Kalaiya",
    "Kolhabi",
    "Mahagadhimai",
    "Nijgadh",
    "Pacharauta",
    "Simraungadh",
    "Dhanusadham",
    "Ganeshman Charnath",
    "Hansapur",
    "Janakpurdham",
    "Kamala",
    "Kshireshwarnath",
    "Mithila",
    "Mithila Bihari",
    "Nagarain",
    "Sabaila",
    "Shahidnagar",
    "Bideha",
    "Aurahi",
    "Balawa",
    "Bardibas",
    "Bhangaha",
    "Gaushala",
    "Jaleshwor",
    "Loharpatti",
    "Manara Shiswa",
    "Matihani",
    "Ramgopalpur",
    "Birgunj",
    "Bahudarmai",
    "Parsagadhi",
    "Pokhariya",
    "Baudhimai",
    "Brindaban",
    "Chandrapur",
    "Dewahi Gonahi",
    "Fatuwa Bijayapur",
    "Gadhimai",
    "Garuda",
    "Gaur",
    "Gujara",
    "Ishanath",
    "Katahariya",
    "Madhav Narayan",
    "Maulapur",
    "Paroha",
    "Rajdevi",
    "Rajpur",
    "Bode Barsain",
    "Dakneshwori",
    "Hanumannagar Kankalini",
    "Kanchanrup",
    "Khadak",
    "Rajbiraj",
    "Saptakoshi",
    "Shambhunath",
    "Surunga",
    "Bagmati",
    "Balara",
    "Barahathwa",
    "Godaita",
    "Haripur",
    "Haripurwa",
    "Hariwan",
    "Ishworpur",
    "Kabilasi",
    "Lalbandi",
    "Malangwa",
    "Dhangadhimai",
    "Golbazar",
    "Kalyanpur",
    "Karjanha",
    "Lahan",
    "Mirchaiya",
    "Siraha",
    "Sukhipur"
  ],

  bagmati: [
    "Bhaktapur",
    "Changunarayan",
    "Madhyapur Thimi",
    "Suryabinayak",
    "Bharatpur",
    "Kalika",
    "Khairahani",
    "Madi",
    "Rapti",
    "Ratnanagar",
    "Dhunibesi",
    "Nilkantha",
    "Bhimeshwar",
    "Jiri",
    "Budhanilkantha",
    "Chandragiri",
    "Dakshinkali",
    "Gokarneshwar",
    "Kageshwari Manohara",
    "Kathmandu",
    "Kirtipur",
    "Nagarjun",
    "Shankharapur",
    "Tarakeshwar",
    "Tokha",
    "Banepa",
    "Dhulikhel",
    "Mandandeupur",
    "Namobuddha",
    "Panauti",
    "Panchkhal",
    "Godawari",
    "Lalitpur",
    "Mahalaxmi",
    "Hetauda",
    "Thaha",
    "Belkotgadhi",
    "Bidur",
    "Manthali",
    "Ramechhap",
    "Dudhauli",
    "Kamalamai",
    "Barhabise",
    "Chautara Sangachokgadhi",
    "Melamchi"
  ],

  gandaki: [
    "Baglung",
    "Dhorpatan",
    "Galkot",
    "Jaimini",
    "Gorkha",
    "Palungtar",
    "Pokhara",
    "Besisahar",
    "Madhyanepal",
    "Rainas",
    "Sundarbazar",
    "Beni",
    "Devchuli",
    "Gaindakot",
    "Kawasoti",
    "Madhyabindu",
    "Kushma",
    "Phalewas",
    "Bhirkot",
    "Chapakot",
    "Galyang",
    "Putalibazar",
    "Waling",
    "Bhanu",
    "Bhimad",
    "Byas",
    "Shuklagandaki"
  ],

  lumbini: [
    "Bhumikasthan",
    "Sandhikharka",
    "Shitganga",
    "Kohalpur",
    "Nepalgunj",
    "Bansgadhi",
    "Barbardiya",
    "Gulariya",
    "Madhuwan",
    "Rajapur",
    "Thakurbaba",
    "Ghorahi",
    "Lamahi",
    "Tulsipur",
    "Musikot",
    "Resunga",
    "Banganga",
    "Buddhabhumi",
    "Kapilvastu",
    "Krishnanagar",
    "Maharajganj",
    "Shivaraj",
    "Bardaghat",
    "Ramgram",
    "Sunwal",
    "Rampur",
    "Tansen",
    "Pyuthan",
    "Swargadwari",
    "Rolpa",
    "Butwal",
    "Devdaha",
    "Lumbini Sanskritik",
    "Sainamaina",
    "Siddharthanagar",
    "Tilottama"
  ],

  karnali: [
    "Aathabis",
    "Chamunda Bindrasaini",
    "Dullu",
    "Narayan",
    "Thuli Bheri",
    "Tripurasundari",
    "Bheri",
    "Chhedagad",
    "Nalgad",
    "Chandannath",
    "Khandachakra",
    "Raskot",
    "Tilagupha",
    "Chhayanath Rara",
    "Aathbiskot",
    "Chaurjahari",
    "Musikot",
    "Bagchaur",
    "Bangad Kupinde",
    "Sharada",
    "Bheriganga",
    "Birendranagar",
    "Gurbhakot",
    "Lekbeshi",
    "Panchapuri"
  ],

  sudurpashchim: [
    "Kamalbazar",
    "Mangalsen",
    "Panchadewal Binayak",
    "Sanphebagar",
    "Dasharathchand",
    "Melauli",
    "Patan",
    "Purchaudi",
    "Bungal",
    "JayaPrithvi",
    "Badimalika",
    "Budhiganga",
    "Budhinanda",
    "Tribeni",
    "Amargadhi",
    "Parshuram",
    "Mahakali",
    "Shailyashikhar",
    "Dipayal Silgadhi",
    "Shikhar",
    "Bhajani",
    "Dhangadhi",
    "Gauriganga",
    "Ghodaghodi",
    "Godawari",
    "Lamki Chuha",
    "Tikapur",
    "Bedkot",
    "Belauri",
    "Bhimdatta",
    "Krishnapur",
    "Punarbas",
    "Shuklaphanta",
    "Dodhara Chandani"
  ]
};